// declare module 'jsbeeb/utils'
// declare module 'jsbeeb/models'
// declare module 'jsbeeb/6502'
// declare module 'jsbeeb/utils'
// declare module 'jsbeeb/fdc'
// declare module 'jsbeeb/cmos'
// declare module 'jsbeeb/video'
// declare module 'jsbeeb/teletext'
// declare module 'jsbeeb/soundchip'

// declare module 'jsbeeb/sound'
// declare module 'jsbeeb/keyboard'
// declare module 'jsbeeb/serial'
// declare module 'jsbeeb/roms'
// declare module 'jsbeeb/disk'
// declare module 'jsbeeb/ddnoise'
// declare module 'jsbeeb/canvas'
// declare module 'jsbeeb/debug'
