# Build, Test, Lint & e2e pushes.
# TODO: use the .nvmrc for node versions
# https://github.com/actions/setup-node/issues/32
name: CI

on:
  # support manual trigger of this workflow
  workflow_dispatch:

  # run this build action for all pushes to main
  push:
    branches: ['master']

  # also run for pull requests that target main
  pull_request:
    branches:
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      # Setup steps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm
        run: npm ci

      - name: Build
        run: npm run package

      - name: Lint
        run: npm run lint

      - name: Test
        run: echo npm run test

